grouped_categories:
  refresh: true
  type: objects
  default: [
    {
      "categoryGroup": "Default Categories",
      "categories": "staff, site-feedback, lounge",
      "security": [
        0
      ]
    }
  ]
  schema:
    name: "Category Groups"
    identifier: categoryGroup
    properties:
      categoryGroup:
        type: string
        required: true
      categories:
        type: string
        required: true
      security:
        type: groups
        min: 1

links:
  refresh: true
  type: objects
  default: [
    {
      "id": "example",
      "url": "https://example.com",
      "color": "#F1592A",
      "title": "Example Link",
      "description": "This is an example link",
      "icon": ""
    }
  ]
  schema:
    name: "Links"
    identifier: id
    properties:
      id:
        type: string
        required: true
      url:
        type: string
        required: true
        url: true
      color:
        type: string
        required: true
      title:
        type: string
        required: true
      description:
        type: string
      icon:
        type: string

show_on_mobile:
  default: true

show_ungrouped:
  default: true

fancy_styling:
  default: false

hide_muted_subcategories:
  default: false
