category_groups:
  type: objects
  default: []
  schema:
    name: category group
    identifier: name
    properties:
      name:
        type: string
        required: true
      categories:
        type: categories
      translations:
        type: objects
        schema:
          name: translation
          identifier: locale
          properties:
            locale:
              type: enum
              required: true
              choices:
                - ar
                - be
                - bg
                - bs_BA
                - ca
                - cs
                - da
                - de
                - el
                - en
                - en_GB
                - es
                - et
                - fa_IR
                - fi
                - fr
                - gl
                - he
                - hr
                - hu
                - hy
                - id
                - it
                - ja
                - ko
                - lt
                - lv
                - nb_NO
                - nl
                - pl_PL
                - pt
                - pt_BR
                - ro
                - ru
                - sk
                - sl
                - sq
                - sr
                - sv
                - sw
                - te
                - th
                - tr_TR
                - ug
                - uk
                - ur
                - vi
                - zh_CN
                - zh_TW
            name:
              type: string
              required: true
extra_links:
  type: objects
  default: []
  schema:
    name: extra link
    identifier: title
    properties:
      id:
        type: string
        required: true
      url:
        type: string
        required: true
      title:
        type: string
        required: true
      color:
        type: string
        required: true
      description:
        type: string
      icon:
        type: string
      show_after:
        type: categories
        validations:
          max: 1

show_on_mobile:
  default: true

show_ungrouped:
  default: true

fancy_styling:
  default: false

hide_muted_subcategories:
  default: false
