category_groups:
  type: "list"
  default: "Default Categories: staff, site-feedback, lounge"
extra_links:
  default: >
    []
  json_schema: >-
    {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "title": "ID",
            "description": "A unique identifier for the link"
          },
          "url": {
            "type": "string",
            "title": "URL",
            "description": "The URL for the link"
          },
          "color": {
            "type": "string",
            "title": "Color",
            "description": "The color associated with the link",
            "format": "color"
          },
          "title": {
            "type": "string",
            "title": "Title",
            "description": "The title of the link"
          },
          "description": {
            "type": "string",
            "format": "markdown",
            "title": "Description",
            "description": "A short description of the link"
          },
          "icon": {
            "type": "string",
            "title": "Icon",
            "description": "An icon for the link. Example: heart",
            "default": ""
          }
        },
        "required": ["id", "url", "title", "color"]
      }
    }

show_on_mobile:
  default: true

show_ungrouped:
  default: true

fancy_styling:
  default: false

hide_muted_subcategories:
  default: false
